/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-dim": "#ddd9d5",
        "primary-container": "#1a2b3c",
        "primary": "#041627",
        "surface-container-high": "#ebe8e3",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "secondary-container": "#fdcb9b",
        "primary-fixed": "#d2e4fb",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e6e2dd",
        "on-tertiary-container": "#cd7880",
        "secondary-fixed": "#ffdcbd",
        "on-secondary-container": "#79542d",
        "tertiary-container": "#4f141d",
        "inverse-primary": "#b7c8de",
        "surface-container": "#f1ede8",
        "on-primary": "#ffffff",
        "on-background": "#1c1c19",
        "outline": "#74777d",
        "secondary": "#7c5730",
        "tertiary-fixed": "#ffdadb",
        "surface-tint": "#4f6073",
        "secondary-fixed-dim": "#eebd8e",
        "surface-container-low": "#f7f3ee",
        "on-secondary-fixed-variant": "#61401b",
        "tertiary": "#33010a",
        "on-primary-container": "#8192a7",
        "background": "#fdf9f4",
        "inverse-on-surface": "#f4f0eb",
        "on-error": "#ffffff",
        "surface": "#fdf9f4",
        "on-tertiary-fixed": "#3c0610",
        "outline-variant": "#c4c6cd",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#44474c",
        "on-primary-fixed": "#0b1d2d",
        "surface-variant": "#e6e2dd",
        "surface-bright": "#fdf9f4",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b7c8de",
        "inverse-surface": "#31302d",
        "on-tertiary-fixed-variant": "#753139",
        "on-primary-fixed-variant": "#38485a",
        "on-surface": "#1c1c19",
        "tertiary-fixed-dim": "#ffb2b8",
        "on-secondary-fixed": "#2c1600",
        "aged-paper": "#E8DFCC",
        "ivory": "#F9F5F0",
        "bronze": "#A67C52",
        "deep-blue": "#1A2B3C"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "unit": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "container-max": "1280px"
      },
      "fontFamily": {
        "display-lg": ["EB Garamond", "serif"],
        "headline-md": ["EB Garamond", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "handwritten": ["Homemade Apple", "cursive"]
      }
    }
  },
  plugins: [],
}
